{
 "title": "otus_l5",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
    }
   },
   {
    "name": "release",
    "label": "Release",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(pg_up{release=\"$release\"})"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } }
  ]
 },
 "panels": [
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count general connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pg_settings_max_connections", "legendFormat": "max_connections" },
    {
     "expr": "sum(pg_stat_activity_count{instance=\"$instance\"})",
     "legendFormat": "total connections"
    },
    {
     "expr": "sum(pg_stat_activity_count{instance=\"$instance\",state=\"idle\"})",
     "legendFormat": "idle sessions"
    },
    {
     "expr": "sum(pg_stat_activity_count{instance=\"$instance\",state=\"active\"})",
     "legendFormat": "active sessions"
    },
    {
     "expr": "sum(pg_stat_activity_count{instance=\"$instance\",state=\"idle in transaction\"})",
     "legendFormat": "idle in transaction sessions"
    },
    {
     "expr": "sum(pg_stat_activity_count{instance=\"$instance\",state=\"idle in transaction (aborted)\"})",
     "legendFormat": "idle in transaction (aborted) sessions"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=\"active\"} !=0",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{release=\"$release\", instance=\"$instance\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"user-service\"}[1m]))",
     "legendFormat": "user-service"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(http_server_requests_seconds_bucket{status!~\"5..\", application=\"user-service\"}[1m])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{status!~\"5..\", application=\"user-service\"}[1m])))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{status!~\"5..\", application=\"user-service\"}[1m])))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{status!~\"5..\", application=\"user-service\"}[1m])))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"user-service\", status=~\"4..|5..\"}[1m]))",
     "legendFormat": "user-service"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"otus-l5\", pod=~\"user-service-app.*\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (pod) (kube_pod_container_resource_limits{namespace=\"otus-l5\", pod=~\"user-service-app.*\", resource=\"cpu\"})",
     "legendFormat": "limit {{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_rss{namespace=\"otus-l5\", pod=~\"user-service-app.*\"}/1024/1024)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (pod) (kube_pod_container_resource_limits{namespace=\"otus-l5\", pod=~\"user-service-app.*\", resource=\"memory\"}/1024/1024)",
     "legendFormat": "limit {{pod}}"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Ingress RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_connect_duration_seconds_count{ingress=\"user-service\"}[1m]))",
     "legendFormat": "user-service"
    }
   ]
  },
  {
   "title": "Ingress latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(nginx_ingress_controller_header_duration_seconds_bucket{status!~\"5..\", ingress=\"user-service\"}[1m])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_header_duration_seconds_bucket{status!~\"5..\", ingress=\"user-service\"}[1m])))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_header_duration_seconds_bucket{status!~\"5..\", ingress=\"user-service\"}[1m])))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_header_duration_seconds_bucket{status!~\"5..\", ingress=\"user-service\"}[1m])))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_connect_duration_seconds_count{ingress=\"user-service\", status=~\"4..|5..\"}[1m]))",
     "legendFormat": "user-service"
    }
   ]
  }
 ]
}